CREATE TABLE post (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author varchar(50) NOT NULL,
    text text NOT NULL,
    created timestamptz NOT NULL DEFAULT NOW(),
    deleted timestamptz
);

CREATE INDEX idx_post_created ON post (created)
WHERE deleted IS NULL;

CREATE VIEW post_view AS SELECT * FROM post;
