use serde::Deserialize;

use crate::{
    diff::{ChangeType, Diff, DiffSql},
    sql::{StatementBuilder, quote_ident},
};

#[derive(Debug, Eq, PartialEq, Deserialize)]
pub struct Column {
    pub name: String,
    pub r#type: String,
    pub notnull: bool,
    pub identity: Identity,
    pub generated: Generated,
    pub default: Option<String>,
}

impl Column {
    pub fn sql(&self) -> String {
        // https://www.postgresql.org/docs/16/sql-createtable.html
        let mut s = StatementBuilder::new();
        s.ident(&self.name);
        s.part(&self.r#type); // FIXME quoting needed for user types/tables?
        match self.generated {
            Generated::No => {}
            Generated::Stored => {
                s.part("GENERATED ALWAYS AS");
                s.part(self.default.as_ref().unwrap());
                s.part("STORED");
            }
        }
        match self.identity {
            Identity::No => {}
            Identity::Default => {
                s.part("GENERATED BY DEFAULT AS IDENTITY");
                if let Some(d) = &self.default {
                    s.part(format!("({})", d));
                }
            }
            Identity::Always => {
                s.part("GENERATED ALWAYS AS IDENTITY");
                if let Some(d) = &self.default {
                    s.part(format!("({})", d));
                }
            }
        }
        if let Some(default) = &self.default {
            s.part("DEFAULT");
            s.part(default);
        }
        if self.notnull {
            s.part("NOT NULL");
        }
        s.to_string()
    }
    pub fn create_sql(&self) -> String {
        format!("ADD COLUMN {}", self.sql())
    }
    pub fn drop_sql(&self) -> String {
        format!("DROP COLUMN {}", quote_ident(&self.name))
    }

    pub fn alter_changes(old: &Self, new: &Self) -> Vec<(ChangeType, String)> {
        if old != new && (old.generated != Generated::No || new.generated != Generated::No) {
            return vec![(
                ChangeType::Unsupported,
                new.unsupported_alter_warning_sql(old),
            )];
        }

        let mut sql = Vec::new();
        if old.r#type != new.r#type {
            sql.push((
                ChangeType::AlterColumn,
                format!(
                "ALTER COLUMN {} TYPE {}",
                quote_ident(&new.name),
                new.r#type
            )));
        }

        match (&old.identity, &new.identity) {
            (Identity::No, Identity::No) => {}
            (Identity::No, Identity::Default) => {
                sql.push((ChangeType::AlterColumn, format!(
                    "ALTER COLUMN {} ADD GENERATED BY DEFAULT AS IDENTITY",
                    quote_ident(&new.name)
                )));
            }
            (Identity::No, Identity::Always) => {
                sql.push((ChangeType::AlterColumn, format!(
                    "ALTER COLUMN {} ADD GENERATED ALWAYS AS IDENTITY",
                    quote_ident(&new.name)
                )));
            }
            (Identity::Default, Identity::Always) => {
                sql.push((ChangeType::AlterColumn, format!(
                    "ALTER COLUMN {} SET GENERATED ALWAYS",
                    quote_ident(&new.name)
                )));
            }
            (Identity::Always, Identity::Default) => {
                sql.push((ChangeType::AlterColumn, format!(
                    "ALTER COLUMN {} SET GENERATED BY DEFAULT",
                    quote_ident(&new.name)
                )));
            }
            (Identity::Default, Identity::No) | (Identity::Always, Identity::No) => {
                sql.push((ChangeType::AlterColumn, format!(
                    "ALTER COLUMN {} DROP IDENTITY IF EXISTS",
                    quote_ident(&new.name)
                )));
            }
            _ => {}
        }

        if old.generated == Generated::No
            && new.generated == Generated::No
            && old.default != new.default
        {
            match &new.default {
                Some(default) => sql.push((ChangeType::AlterColumn, format!(
                    "ALTER COLUMN {} SET DEFAULT {}",
                    quote_ident(&new.name),
                    default
                ))),
                None => sql.push((ChangeType::AlterColumn, format!(
                    "ALTER COLUMN {} DROP DEFAULT",
                    quote_ident(&new.name)
                ))),
            }
        }

        if old.notnull != new.notnull {
            sql.push((ChangeType::AlterColumn, format!(
                "ALTER COLUMN {} {}",
                quote_ident(&new.name),
                if new.notnull {
                    "SET NOT NULL"
                } else {
                    "DROP NOT NULL"
                }
            )));
        }

        sql
    }

    pub fn unsupported_alter_warning_sql(&self, previous: &Self) -> String {
        format!(
            "-- WARNING: column {} has an unsupported schema change and no safe automatic migration was generated.\n\
-- Previous generated state: {:?}\n\
-- Target generated state: {:?}\n\
-- Previous expression/default payload: {}\n\
-- Target expression/default payload: {}\n\
-- Suggested manual approach:\n\
-- 1. Add a replacement column with the desired generated definition.\n\
-- 2. Rewrite dependent indexes, constraints, or queries.\n\
-- 3. Drop the old column and rename the replacement column.\n\
",
            quote_ident(&self.name),
            previous.generated,
            self.generated,
            previous.default.as_deref().unwrap_or("NULL"),
            self.default.as_deref().unwrap_or("NULL"),
        )
    }
}

#[derive(Debug, Eq, PartialEq, Deserialize)]
pub enum Generated {
    #[serde(rename = "")]
    No,
    #[serde(rename = "s")]
    Stored,
}

#[derive(Debug, Eq, PartialEq, Deserialize)]
pub enum Identity {
    #[serde(rename = "")]
    No,
    #[serde(rename = "a")]
    Always,
    #[serde(rename = "d")]
    Default,
}

impl DiffSql for Diff<'_, Column> {
    fn sql(&self) -> Vec<(ChangeType, String)> {
        let mut v = Vec::new();
        for a in &self.a_only {
            v.push((ChangeType::DropColumn, a.drop_sql()));
        }
        for (a, b) in &self.a_and_b {
            if a != b {
                v.extend(Column::alter_changes(a, b));
            }
        }
        for b in &self.b_only {
            v.push((ChangeType::CreateColumn, b.create_sql()));
        }
        v
    }
}
