[package]
name = "tusker-query-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.20.3"
quote = "1.0.33"
serde_json = "1.0.108"
syn = "2.0.39"
