name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  msrv:
    name: Check MSRV
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly
      - run: rustup update 1.85 && rustup default 1.85
      - run: cargo +nightly update -Z direct-minimal-versions
      - run: cargo check --all-features

  test:
    name: Run tests
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:17-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: tusker
          POSTGRES_PASSWORD: tusker
          POSTGRES_DB: tusker
        # Health checks to wait until Postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --all-features --workspace
      - name: Run tests
        run: cargo test --all-features --workspace
        env:
          PG_URL: host=127.0.0.1 port=5432 user=tusker password=tusker dbname=tusker
