name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: tusker
          POSTGRES_PASSWORD: tusker
          POSTGRES_DB: tusker
        # Health checks to wait until Postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --all-features --workspace
    - name: Run tests
      run: cargo test --verbose --all-features --workspace
      env:
        PG_URL: host=127.0.0.1 port=5432 user=tusker password=tusker dbname=tusker"
